version: '3.9'

volumes:
  postgres-data:
  postgres-data2:

services:
  postgres:
    image: postgres:latest
    container_name: parrot_db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=dev
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
      # copy the sql script to create tables
      - ./sql/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    restart: always
  postgres2:
    image: postgres:latest
    container_name: parrot_db_2
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=dev
    ports:
      - 5433:5432
    volumes:
      - postgres-data2:/var/lib/postgresql/data
      # copy the sql script to create tables
      - ./sql/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    restart: always
